# Docker compose file for Linux/Debian deployment
version: '3.8'

services:
  course-agent-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount Docker socket to allow container to run other containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/qais_jabbar/drive-credentials:/credentials
    environment:
      - PYTHONUNBUFFERED=1
      - CREDENTIALS_BASE_PATH=/credentials
      - HOST_CREDENTIALS_PATH=/home/qais_jabbar/drive-credentials 
      - DOCKER_NETWORK=tara-ai-ml-agent_course-agent-network 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - course-agent-network

networks:
  course-agent-network:
    driver: bridge
