name: Deploy Docker Compose to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Compute Engine
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: 'projects/1039211957160/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'sa-tara@id-rd-ca-qais-jabbar.iam.gserviceaccount.com'
    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v2'
      with:
        instance_name: 'tara-vm'
        zone: 'us-central1-a'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
          sudo su -c "
            cd /home/qais_jabbar/tara-ai-ml-agent &&
            git pull origin main &&
            docker compose up --build -d
          "